[package]
name = "c100"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.30"
rayon = "1.8.0"
proclib = {path = "./proclib/"}